server:
  port: 1031

spring:
  application:
    name: demo-springcloud-consumer
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ipAddress}:${server.port}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    
feign:
  hystrix:
    enabled: true
    
hystrix:
#  threadpool:
#    default:
#      coreSize: 10  #并发执行的最大线程数，默认10  
#  command:
#    paas-file:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3600000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000  #命令执行超时时间，默认1000ms