server:
  port: 1041
  tomcat:
   max-threads: 50 # tomcat 线程数（50 比较小，只是本地测试用）
   
spring:
  application:
    name: demo-springcloud-zuul
    
zuul:
  ignoredServices: '*'
  routes:
    provider:
      path: /api/v1/provider/**
      service-id: demo-springcloud-provider
    product:
      path: /api/v1/product/**
      service-id: demo-springcloud-product
      
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 执行是否启用超时，默认启用 true
        isolation:
          thread:
            timeoutInMilliseconds: 60000  # 命令执行超时时间，默认1000ms
            interruptOnTimeout: false # 发生超时是是否中断，默认 true
#  threadpool:
#    default:
#      coreSize: 10  #并发执行的最大线程数，默认10

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000    
      
management:
  security:
    enabled: false      