spring:
  datasource:
    url: jdbc:mysql://192.168.1.118:8066/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz@WSX
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none